import fs from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const workDir = path.join(root, '.newsroom');
const draftPath = path.join(workDir, 'drafts.json');
const newsPath = path.join(root, 'news-data.json');
const summaryPath = path.join(workDir, 'pr-summary.md');

const draftsPayload = JSON.parse(await fs.readFile(draftPath, 'utf8'));
const news = JSON.parse(await fs.readFile(newsPath, 'utf8'));
const drafts = draftsPayload.drafts || [];

if (!drafts.length) {
  await fs.writeFile(summaryPath, '# GCT Daily automated review\n\nNo verified drafts met the publication threshold in this run.\n');
  console.log('GCT newsroom: no verified drafts to propose.');
  process.exit(0);
}

const existingSlugs = new Set((news.stories || []).map(s => s.slug));
const additions = drafts.filter(d => !existingSlugs.has(d.slug));

if (!additions.length) {
  await fs.writeFile(summaryPath, '# GCT Daily automated review\n\nAll verified drafts were already present in the publication data.\n');
  console.log('GCT newsroom: verified drafts were already present.');
  process.exit(0);
}

const existing = (news.stories || []).map(s => ({ ...s, featured: false }));
const proposed = additions.map((story, index) => ({ ...story, featured: index === 0 }));
news.stories = [...proposed, ...existing];
news.publication = {
  ...(news.publication || {}),
  updatedAt: new Date().toISOString()
};

await fs.writeFile(newsPath, `${JSON.stringify(news, null, 2)}\n`);
await fs.writeFile(summaryPath, buildSummary(proposed));
console.log(`GCT newsroom: proposed ${proposed.length} verified story draft(s). Merging the generated PR will publish them.`);

function buildSummary(stories) {
  const lines = [
    '# GCT Daily automated editorial review',
    '',
    '> **Approval model:** merging this PR publishes these stories. Do not merge until the copy and source links have been reviewed.',
    '',
    `Stories proposed: **${stories.length}**`,
    ''
  ];

  for (const story of stories) {
    lines.push(`## ${story.title}`);
    lines.push('');
    lines.push(`- **Category:** ${story.category}`);
    lines.push(`- **Verification confidence:** ${story.verificationConfidence}/100`);
    lines.push(`- **Heuristic discovery score:** ${story.automation?.heuristicScore ?? 'n/a'}/100`);
    lines.push(`- **Discovery publisher:** ${story.automation?.discoveryPublisher || 'n/a'}`);
    lines.push('');
    lines.push('### Sources');
    lines.push('');
    for (const source of story.sources || []) {
      lines.push(`- ${source.sourceType === 'primary' ? '**Primary**' : 'Secondary'} — [${source.title}](${source.url})`);
    }
    lines.push('');
    lines.push('### Proposed framing');
    lines.push('');
    lines.push(`**What happened:** ${story.whatHappened}`);
    lines.push('');
    lines.push(`**Why it matters:** ${story.whyItMatters}`);
    lines.push('');
    lines.push(`**GCT Take:** ${story.gctTake}`);
    lines.push('');

    if ((story.commercialSignals || []).length) {
      lines.push('### Internal commercial signals');
      lines.push('');
      for (const signal of story.commercialSignals) {
        lines.push(`- **${signal.entity} — ${signal.priority}:** ${signal.signal}. ${signal.opportunity}${signal.doNotContactReason ? ` _Do not contact / caution: ${signal.doNotContactReason}_` : ''}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('Generated by the GCT Daily newsroom scout. AI verification assists editorial review; the human reviewer remains the final publisher.');
  lines.push('');
  return `${lines.join('\n')}\n`;
}
